paths:
  /users/me:
    get:
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    example: 105
                  email:
                    type: string
                    example: bruce@gmail.com
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
