paths:
  /auth/register:
    post:
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: bruce@gmail.com
                password:
                  type: string
                  example: 123456
      responses:
        '201':
          description: The user has been created
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6ImJydWNlQGdtYWlsLmNvbSJ9LCJpYXQiOjE2NDk2MDQ4MzksImV4cCI6MTY0OTYwODQzOX0.Hun__fEeEaHZgyuHuhvX-hCvxohVDfu9x4ZhXRWa4QE'
                  expires:
                    type: number
                    example: 3600
                  refreshToken:
                    type: string
                    example: d744c2b1-10ba-4b41-9032-d1f68dd5ad6f
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                          example: 400
                        message:
                          type: string
                          example: The email field is required
        '409':
          description: The user already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                          example: 409
                        message:
                          type: string
                          example: Email already exists

  /auth/login:
    post:
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: bruce@gmail.com
                password:
                  type: string
                  example: 123456
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6ImJydWNlQGdtYWlsLmNvbSJ9LCJpYXQiOjE2NDk2MDQ4MzksImV4cCI6MTY0OTYwODQzOX0.Hun__fEeEaHZgyuHuhvX-hCvxohVDfu9x4ZhXRWa4QE'
                  expires:
                    type: number
                    example: 3600
                  refreshToken:
                    type: string
                    example: d744c2b1-10ba-4b41-9032-d1f68dd5ad6f
        '400':
          description: Bad Request. The message could be "The email does not exist",
            "The password is not valid", or when there is a missed attribute,
            the message is '"password" is required' and the property 'field' with the value 'password'
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                          example: 400
                        message:
                          type: string
                          example: The email field is required

  /auth/refresh-token:
    post:
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
                  example: d744c2b1-10ba-4b41-9032-d1f68dd5ad6f
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6ImJydWNlQGdtYWlsLmNvbSJ9LCJpYXQiOjE2NDk2MDQ4MzksImV4cCI6MTY0OTYwODQzOX0.Hun__fEeEaHZgyuHuhvX-hCvxohVDfu9x4ZhXRWa4QE'
                  expires:
                    type: number
                    example: 3600
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                          example: 401
                        message:
                          type: string
                          example: Unauthorized
